name: Deploy Plugin to Server

on: push

env:
  PLUGIN_SERVER_PATH: public_html/website_1e1b7ec3/
  PLUGIN_NAME: bluehost-wordpress-plugin
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@newfold-labs"

      - name: Authenticate with GitHub Packages
        run: |
          echo "@newfold-labs:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc

      - name: Install PHP and Composer
        run: |
          sudo apt update
          sudo apt install -y php-cli unzip curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node dependencies and build project
        run: |
          npm install
          npm run create:dev

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: ./bluehost-wordpress-plugin.zip

      - name: Setup SSH Key
        run: |
            echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > github-actions
            chmod 600 github-actions

      - name: Copy .zip file to server via SCP
        run: |
          scp -i github-actions -o StrictHostKeyChecking=no ./bluehost-wordpress-plugin.zip ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ env.PLUGIN_SERVER_PATH }}/wp-content/uploads

      - name: Extract Plugin and Activate
        run: |
          ssh -i github-actions -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ env.PLUGIN_SERVER_PATH }}/wp-content/plugins
            unzip -o ../uploads/bluehost-wordpress-plugin.zip -d .
            rm ../uploads/bluehost-wordpress-plugin.zip
            wp plugin activate ${{ env.PLUGIN_NAME }} --path=${{ env.PLUGIN_SERVER_PATH }}
          EOF

      - name: Cleanup SSH Key
        run: rm -f github-actions